spring.application.name=To-do-list
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=Maheki

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
